const tatCaSanPham = [
  // === MÁY GIẶT ===
  {
    maSP: 1,
    tenSP: "Máy giặt LG Inverter 9kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "8.500.000đ",
    giamGia: "-10%",
    giaHienTai: "7.650.000đ",
    giaSo: 7650000,
    soLuong: 30,
    nguongCanhBao: 5,
    thuongHieu: "LG",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=1",
  },
  {
    maSP: 2,
    tenSP: "Máy giặt Samsung AddWash 10kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "10.200.000đ",
    giamGia: "-12%",
    giaHienTai: "8.976.000đ",
    giaSo: 8976000,
    soLuong: 20,
    nguongCanhBao: 5,
    thuongHieu: "Samsung",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=2",
  },
  {
    maSP: 3,
    tenSP: "Máy giặt Toshiba Inverter 8.5kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "7.900.000đ",
    giamGia: "-7%",
    giaHienTai: "7.347.000đ",
    giaSo: 7347000,
    soLuong: 25,
    nguongCanhBao: 5,
    thuongHieu: "Toshiba",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=3",
  },
  {
    maSP: 4,
    tenSP: "Máy giặt Aqua 9kg cửa trên",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "6.800.000đ",
    giamGia: "-5%",
    giaHienTai: "6.460.000đ",
    giaSo: 6460000,
    soLuong: 40,
    nguongCanhBao: 5,
    thuongHieu: "Aqua",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=4",
  },
  {
    maSP: 5,
    tenSP: "Máy giặt Electrolux 9kg Inverter",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "9.600.000đ",
    giamGia: "-10%",
    giaHienTai: "8.640.000đ",
    giaSo: 8640000,
    soLuong: 18,
    nguongCanhBao: 5,
    thuongHieu: "Electrolux",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=5",
  },
  {
    maSP: 6,
    tenSP: "Máy giặt Panasonic 10kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "8.000.000đ",
    giamGia: "-8%",
    giaHienTai: "7.360.000đ",
    giaSo: 7360000,
    soLuong: 22,
    nguongCanhBao: 5,
    thuongHieu: "Panasonic",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=6",
  },
  {
    maSP: 7,
    tenSP: "Máy giặt Casper Inverter 8.5kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "6.500.000đ",
    giamGia: "-9%",
    giaHienTai: "5.915.000đ",
    giaSo: 5915000,
    soLuong: 27,
    nguongCanhBao: 5,
    thuongHieu: "Casper",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=7",
  },
  {
    maSP: 8,
    tenSP: "Máy giặt Sharp 9kg cửa trên",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "6.000.000đ",
    giamGia: "-7%",
    giaHienTai: "5.580.000đ",
    giaSo: 5580000,
    soLuong: 35,
    nguongCanhBao: 5,
    thuongHieu: "Sharp",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=8",
  },
  {
    maSP: 9,
    tenSP: "Máy giặt Midea 7.5kg",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "5.200.000đ",
    giamGia: "-6%",
    giaHienTai: "4.888.000đ",
    giaSo: 4888000,
    soLuong: 30,
    nguongCanhBao: 5,
    thuongHieu: "Midea",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=9",
  },
  {
    maSP: 10,
    tenSP: "Máy giặt Beko 8kg Inverter",
    loaiSP: "may_giat",
    hinhAnh: "",
    giaGoc: "7.300.000đ",
    giamGia: "-10%",
    giaHienTai: "6.570.000đ",
    giaSo: 6570000,
    soLuong: 20,
    nguongCanhBao: 5,
    thuongHieu: "Beko",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=10",
  },

  // === TV ===
  {
    maSP: 11,
    tenSP: "TV Samsung 43 inch 4K UHD",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "10.000.000đ",
    giamGia: "-10%",
    giaHienTai: "9.000.000đ",
    giaSo: 9000000,
    soLuong: 15,
    nguongCanhBao: 3,
    thuongHieu: "Samsung",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=11",
  },
  {
    maSP: 12,
    tenSP: "TV LG 55 inch OLED",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "22.000.000đ",
    giamGia: "-15%",
    giaHienTai: "18.700.000đ",
    giaSo: 18700000,
    soLuong: 10,
    nguongCanhBao: 3,
    thuongHieu: "LG",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=12",
  },
  {
    maSP: 13,
    tenSP: "TV Sony 50 inch 4K HDR",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "17.000.000đ",
    giamGia: "-12%",
    giaHienTai: "14.960.000đ",
    giaSo: 14960000,
    soLuong: 12,
    nguongCanhBao: 3,
    thuongHieu: "Sony",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=13",
  },
  {
    maSP: 14,
    tenSP: "TV TCL 43 inch Smart TV",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "8.500.000đ",
    giamGia: "-10%",
    giaHienTai: "7.650.000đ",
    giaSo: 7650000,
    soLuong: 18,
    nguongCanhBao: 3,
    thuongHieu: "TCL",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=14",
  },
  {
    maSP: 15,
    tenSP: "TV Casper 43 inch Full HD",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "7.200.000đ",
    giamGia: "-9%",
    giaHienTai: "6.552.000đ",
    giaSo: 6552000,
    soLuong: 16,
    nguongCanhBao: 3,
    thuongHieu: "Casper",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=15",
  },
  {
    maSP: 16,
    tenSP: "TV Xiaomi 50 inch 4K",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "10.500.000đ",
    giamGia: "-10%",
    giaHienTai: "9.450.000đ",
    giaSo: 9450000,
    soLuong: 14,
    nguongCanhBao: 3,
    thuongHieu: "Xiaomi",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=16",
  },
  {
    maSP: 17,
    tenSP: "TV Panasonic 55 inch 4K",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "19.000.000đ",
    giamGia: "-13%",
    giaHienTai: "16.530.000đ",
    giaSo: 16530000,
    soLuong: 8,
    nguongCanhBao: 3,
    thuongHieu: "Panasonic",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=17",
  },
  {
    maSP: 18,
    tenSP: "TV Sharp 40 inch HD",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "6.500.000đ",
    giamGia: "-8%",
    giaHienTai: "5.980.000đ",
    giaSo: 5980000,
    soLuong: 25,
    nguongCanhBao: 3,
    thuongHieu: "Sharp",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=18",
  },
  {
    maSP: 19,
    tenSP: "TV Toshiba 43 inch Smart",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "9.000.000đ",
    giamGia: "-11%",
    giaHienTai: "8.010.000đ",
    giaSo: 8010000,
    soLuong: 20,
    nguongCanhBao: 3,
    thuongHieu: "Toshiba",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=19",
  },
  {
    maSP: 20,
    tenSP: "TV Beko 43 inch Android",
    loaiSP: "tv",
    hinhAnh: "",
    giaGoc: "8.000.000đ",
    giamGia: "-10%",
    giaHienTai: "7.200.000đ",
    giaSo: 7200000,
    soLuong: 22,
    nguongCanhBao: 3,
    thuongHieu: "Beko",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=20",
  },
  
  // === (CÒN: TỦ LẠNH, MÁY LẠNH, MÁY LỌC KHÔNG KHÍ) ===
    // === TỦ LẠNH ===
  {
    maSP: 21,
    tenSP: "Tủ lạnh LG Inverter 315 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "12.000.000đ",
    giamGia: "-10%",
    giaHienTai: "10.800.000đ",
    giaSo: 10800000,
    soLuong: 15,
    nguongCanhBao: 3,
    thuongHieu: "LG",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=21",
  },
  {
    maSP: 22,
    tenSP: "Tủ lạnh Samsung 2 cửa 340 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "13.000.000đ",
    giamGia: "-12%",
    giaHienTai: "11.440.000đ",
    giaSo: 11440000,
    soLuong: 12,
    nguongCanhBao: 3,
    thuongHieu: "Samsung",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=22",
  },
  {
    maSP: 23,
    tenSP: "Tủ lạnh Toshiba Inverter 280 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "10.500.000đ",
    giamGia: "-9%",
    giaHienTai: "9.555.000đ",
    giaSo: 9555000,
    soLuong: 18,
    nguongCanhBao: 3,
    thuongHieu: "Toshiba",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=23",
  },
  {
    maSP: 24,
    tenSP: "Tủ lạnh Panasonic 300 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "11.000.000đ",
    giamGia: "-10%",
    giaHienTai: "9.900.000đ",
    giaSo: 9900000,
    soLuong: 10,
    nguongCanhBao: 3,
    thuongHieu: "Panasonic",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=24",
  },
  {
    maSP: 25,
    tenSP: "Tủ lạnh Aqua 260 lít ngăn đá trên",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "8.500.000đ",
    giamGia: "-8%",
    giaHienTai: "7.820.000đ",
    giaSo: 7820000,
    soLuong: 22,
    nguongCanhBao: 3,
    thuongHieu: "Aqua",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=25",
  },
  {
    maSP: 26,
    tenSP: "Tủ lạnh Sharp 196 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "6.900.000đ",
    giamGia: "-7%",
    giaHienTai: "6.417.000đ",
    giaSo: 6417000,
    soLuong: 28,
    nguongCanhBao: 3,
    thuongHieu: "Sharp",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=26",
  },
  {
    maSP: 27,
    tenSP: "Tủ lạnh Casper Inverter 250 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "8.000.000đ",
    giamGia: "-10%",
    giaHienTai: "7.200.000đ",
    giaSo: 7200000,
    soLuong: 16,
    nguongCanhBao: 3,
    thuongHieu: "Casper",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=27",
  },
  {
    maSP: 28,
    tenSP: "Tủ lạnh Beko 200 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "6.500.000đ",
    giamGia: "-10%",
    giaHienTai: "5.850.000đ",
    giaSo: 5850000,
    soLuong: 30,
    nguongCanhBao: 3,
    thuongHieu: "Beko",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=28",
  },
  {
    maSP: 29,
    tenSP: "Tủ lạnh Midea 220 lít ngăn đá dưới",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "7.500.000đ",
    giamGia: "-8%",
    giaHienTai: "6.900.000đ",
    giaSo: 6900000,
    soLuong: 25,
    nguongCanhBao: 3,
    thuongHieu: "Midea",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=29",
  },
  {
    maSP: 30,
    tenSP: "Tủ lạnh Xiaomi 2 cửa 260 lít",
    loaiSP: "tu_lanh",
    hinhAnh: "",
    giaGoc: "9.500.000đ",
    giamGia: "-10%",
    giaHienTai: "8.550.000đ",
    giaSo: 8550000,
    soLuong: 15,
    nguongCanhBao: 3,
    thuongHieu: "Xiaomi",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=30",
  },

  // === MÁY LẠNH ===
  {
    maSP: 31,
    tenSP: "Máy lạnh LG Inverter 1.5HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "11.000.000đ",
    giamGia: "-12%",
    giaHienTai: "9.680.000đ",
    giaSo: 9680000,
    soLuong: 20,
    nguongCanhBao: 4,
    thuongHieu: "LG",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=31",
  },
  {
    maSP: 32,
    tenSP: "Máy lạnh Daikin Inverter 1HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "10.500.000đ",
    giamGia: "-10%",
    giaHienTai: "9.450.000đ",
    giaSo: 9450000,
    soLuong: 22,
    nguongCanhBao: 4,
    thuongHieu: "Daikin",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=32",
  },
  {
    maSP: 33,
    tenSP: "Máy lạnh Panasonic Inverter 1.5HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "12.000.000đ",
    giamGia: "-10%",
    giaHienTai: "10.800.000đ",
    giaSo: 10800000,
    soLuong: 18,
    nguongCanhBao: 4,
    thuongHieu: "Panasonic",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=33",
  },
  {
    maSP: 34,
    tenSP: "Máy lạnh Casper Inverter 1.5HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "8.800.000đ",
    giamGia: "-8%",
    giaHienTai: "8.096.000đ",
    giaSo: 8096000,
    soLuong: 25,
    nguongCanhBao: 4,
    thuongHieu: "Casper",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=34",
  },
  {
    maSP: 35,
    tenSP: "Máy lạnh Toshiba 1HP Inverter",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "9.500.000đ",
    giamGia: "-9%",
    giaHienTai: "8.645.000đ",
    giaSo: 8645000,
    soLuong: 20,
    nguongCanhBao: 4,
    thuongHieu: "Toshiba",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=35",
  },
  {
    maSP: 36,
    tenSP: "Máy lạnh Samsung WindFree 1HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "11.500.000đ",
    giamGia: "-11%",
    giaHienTai: "10.235.000đ",
    giaSo: 10235000,
    soLuong: 15,
    nguongCanhBao: 4,
    thuongHieu: "Samsung",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=36",
  },
  {
    maSP: 37,
    tenSP: "Máy lạnh Midea Inverter 1HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "7.500.000đ",
    giamGia: "-10%",
    giaHienTai: "6.750.000đ",
    giaSo: 6750000,
    soLuong: 30,
    nguongCanhBao: 4,
    thuongHieu: "Midea",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=37",
  },
  {
    maSP: 38,
    tenSP: "Máy lạnh Beko Inverter 1.5HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "8.200.000đ",
    giamGia: "-9%",
    giaHienTai: "7.462.000đ",
    giaSo: 7462000,
    soLuong: 26,
    nguongCanhBao: 4,
    thuongHieu: "Beko",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=38",
  },
  {
    maSP: 39,
    tenSP: "Máy lạnh Aqua Inverter 1HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "8.000.000đ",
    giamGia: "-10%",
    giaHienTai: "7.200.000đ",
    giaSo: 7200000,
    soLuong: 28,
    nguongCanhBao: 4,
    thuongHieu: "Aqua",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=39",
  },
  {
    maSP: 40,
    tenSP: "Máy lạnh Sharp Inverter 1HP",
    loaiSP: "may_lanh",
    hinhAnh: "",
    giaGoc: "7.800.000đ",
    giamGia: "-8%",
    giaHienTai: "7.176.000đ",
    giaSo: 7176000,
    soLuong: 24,
    nguongCanhBao: 4,
    thuongHieu: "Sharp",
    tinhTrang: "Còn hàng",
    lienKet: "./product-details.html?id=40",
  },

  // === MÁY LỌC KHÔNG KHÍ ===
  { maSP: 41, tenSP: "Máy lọc không khí Sharp FP-J40E-W", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "4.000.000đ", giamGia: "-15%", giaHienTai: "3.400.000đ", giaSo: 3400000, soLuong: 100, nguongCanhBao: 10, thuongHieu: "Sharp", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=41" },
  { maSP: 42, tenSP: "Máy lọc không khí Daikin MC30VVM-A", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "3.200.000đ", giamGia: "-10%", giaHienTai: "2.880.000đ", giaSo: 2880000, soLuong: 80, nguongCanhBao: 10, thuongHieu: "Daikin", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=42" },
  { maSP: 43, tenSP: "Máy lọc không khí Xiaomi Air Purifier 4 Pro", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "5.000.000đ", giamGia: "-12%", giaHienTai: "4.400.000đ", giaSo: 4400000, soLuong: 60, nguongCanhBao: 5, thuongHieu: "Xiaomi", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=43" },
  { maSP: 44, tenSP: "Máy lọc không khí Philips AC1215/10", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "4.200.000đ", giamGia: "-10%", giaHienTai: "3.780.000đ", giaSo: 3780000, soLuong: 90, nguongCanhBao: 10, thuongHieu: "Philips", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=44" },
  { maSP: 45, tenSP: "Máy lọc không khí Coway AP-1009CH", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "6.500.000đ", giamGia: "-8%", giaHienTai: "5.980.000đ", giaSo: 5980000, soLuong: 50, nguongCanhBao: 5, thuongHieu: "Coway", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=45" },
  { maSP: 46, tenSP: "Máy lọc không khí LG PuriCare AS65GDW0", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "8.900.000đ", giamGia: "-10%", giaHienTai: "8.010.000đ", giaSo: 8010000, soLuong: 40, nguongCanhBao: 5, thuongHieu: "LG", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=46" },
  { maSP: 47, tenSP: "Máy lọc không khí Panasonic F-PXJ30A", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "4.500.000đ", giamGia: "-9%", giaHienTai: "4.095.000đ", giaSo: 4095000, soLuong: 70, nguongCanhBao: 10, thuongHieu: "Panasonic", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=47" },
  { maSP: 48, tenSP: "Máy lọc không khí Hitachi EP-A3000", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "6.200.000đ", giamGia: "-12%", giaHienTai: "5.456.000đ", giaSo: 5456000, soLuong: 55, nguongCanhBao: 5, thuongHieu: "Hitachi", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=48" },
  { maSP: 49, tenSP: "Máy lọc không khí Blueair Blue Pure 411", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "3.800.000đ", giamGia: "-10%", giaHienTai: "3.420.000đ", giaSo: 3420000, soLuong: 65, nguongCanhBao: 10, thuongHieu: "Blueair", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=49" },
  { maSP: 50, tenSP: "Máy lọc không khí Levoit Core 300S", loaiSP: "may_loc_khong_khi", hinhAnh: "", giaGoc: "5.000.000đ", giamGia: "-10%", giaHienTai: "4.500.000đ", giaSo: 4500000, soLuong: 60, nguongCanhBao: 10, thuongHieu: "Levoit", tinhTrang: "Còn hàng", lienKet: "./product-details.html?id=50" },
];

// đẩy lên local
// truyền vô tên key và object chứa data
setlocalStorage("product", tatCaSanPham);
function setlocalStorage(key, value){
    localStorage.setItem(key, JSON.stringify(value));
}
// lấy file từ local
// truyền vô key để lấy data
function getlocalStorage(key){
    return JSON.parse(localStorage.getItem(key));
}

// const bangSp = getlocalStorage('product');
// console.log(bangSp);


